### ISSUE TITLE
 a javascript error occurred in the main process

### ISSUE THREAD

**Issue by yangchris4** [xanderfrangos/twinkle-tray#246]
**a javascript error occurred in the main process**

Uncaught Exception:
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:705:16)
    at C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1032:20
    at new Promise (<anonymous>)
    at refreshMonitorsJob (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1031:16)
    at refreshMonitors (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1091:25)
    at IpcMainImpl.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1374:3)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9692)
    at Object.emit (events.js:315:20)

![Snipaste_2021-09-26_09-28-08](https://user-images.githubusercontent.com/13220804/134790114-2fb0743c-c707-41d8-9526-1d43bf311ad9.png)

**Comment by menghu1994** [comment]
The same fault,and the solution from the Internet can not work.

**Comment by UnacceptableUse** [comment]
Same issue here.

**Comment by LPFchan** [comment]
Yep, same issue here as well. I'm currently on 22494.1000

**Comment by CeoOfFry** [comment]
same, 22499.1000

**Comment by Abysmax** [comment]
Same

**Comment by xanderfrangos** [comment]
It seems to primarily be a Windows 11 Insider issue, though some Windows 10 users are having it as well. I'll be looking into the issue this weekend. For now, I'm going to pin this Issue and point similar ones here. I may post an test version to this Issue for people to try if they'd like to help.

**Comment by xanderfrangos** [comment]
Good news, I've found the source of the problem on Windows 11 Insider builds:
https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/

Bad news, I don't currently have an alternative. I might need to find a new way to access WMI via Node...

**Comment by xanderfrangos** [comment]
I don't yet have a fix for WMIC being unavailable in newer Windows 11 Insider builds, but I have improved error handling relating to the error message. The following build of Twinkle Tray should work fine for DDC/CI displays on any version of Windows 11:

https://1drv.ms/u/s!AiWKFpjcSKRQhskFgapyA5bewKf4IQ?e=4qYD3G

Your laptop's internal display will NOT be listed in Twinkle Tray on this build if you are in the Windows 11 Insider program. However, if you guys can let me know if external monitors are working (and the UI in general) in the above version of Twinkle Tray, it would be greatly appreciated.

**Comment by UnacceptableUse** [comment]
Can confirm on Windows 11 22499 with that version all of my external displays are listed. Thanks!

**Comment by anhtuan23** [comment]
It's working as stated on my Windows 11 22499 too.

**Comment by TheSiZaGaming** [comment]
On the latest version of the Windows Insider Preview for Windows 11, I receive the same error whenever I try to access the tray icon, or use the interface in any way. The build number is 22504.1000 and I think this might be the case thanks to Microsoft's removal of WMIC as listed above. Your idea for this project is amazing, and I do hope you find a workaround soon.

**Comment by yan1019** [comment]
> I don't yet have a fix for WMIC being unavailable in newer Windows 11 Insider builds, but I have improved error handling relating to the error message. The following build of Twinkle Tray should work fine for DDC/CI displays on any version of Windows 11:
> 
> https://1drv.ms/u/s!AiWKFpjcSKRQhskFgapyA5bewKf4IQ?e=4qYD3G
> 
> Your laptop's internal display will NOT be listed in Twinkle Tray on this build if you are in the Windows 11 Insider program. However, if you guys can let me know if external monitors are working (and the UI in general) in the above version of Twinkle Tray, it would be greatly appreciated.

This version runs normally on my Windows 11 Insider Preview 22499.1010 system, all functions are normal

**Comment by xanderfrangos** [comment]
Great, thanks for confirming! I have one more test version for you all before I release an update. It'll probably be a little while before I can address the lack of WMIC, but I can at least get rid of the errors for now.

Anyway, let me know if this one is still OK on 22499+:
https://1drv.ms/u/s!AiWKFpjcSKRQhskH-JyFYD1pq-8jbg?e=lj3mmJ

**Comment by dejwi** [comment]
> Great, thanks for confirming! I have one more test version for you all before I release an update. It'll probably be a little while before I can address the lack of WMIC, but I can at least get rid of the errors for now.
> 
> Anyway, let me know if this one is still OK on 22499+: https://1drv.ms/u/s!AiWKFpjcSKRQhskH-JyFYD1pq-8jbg?e=lj3mmJ

Windows 11 Insider Preview 10.0.22499.1010 works good

**Comment by RgazHTale** [comment]
> **a javascript error occurred in the main process**
> 
> Uncaught Exception: Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed at ChildProcess.target.send (internal/child_process.js:705:16) at C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1032:20 at new Promise () at refreshMonitorsJob (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1031:16) at refreshMonitors (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1091:25) at IpcMainImpl. (C:\Users\Administrator\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1374:3) at IpcMainImpl.emit (events.js:315:20) at Object. (electron/js2c/browser_init.js:161:9692) at Object.emit (events.js:315:20)
> 
> ![Snipaste_2021-09-26_09-28-08](https://user-images.githubusercontent.com/13220804/134790114-2fb0743c-c707-41d8-9526-1d43bf311ad9.png)

Same error occur on my win10. I solved the error by reinstall win10. Now my computer is win11. Everything is ok.

**Comment by RgazHTale** [comment]
Same error occur on my win10. I solved the error by reinstall win10. Now my computer is win11. Everything is ok.

**Comment by xanderfrangos** [comment]
Hi all,

I've released v1.13.11 with a full replacement for WMIC. This means the Twinkle Tray should work correctly on all builds of Windows 11 now. Let me know if you guys run into any issues.

I'm holding off on a Windows Store update for a day or two to see if anyone reports new bugs related to the WMIC replacement. So if you want to test and are using the Windows Store version, so you should uninstall that and use the EXE from GitHub.

**Comment by RakSrinaNa** [comment]
Any update on publishing it on Windows Store?

**Comment by xanderfrangos** [comment]
> Any update on publishing it on Windows Store?

Some users are having issues with the new C++ bindings, so I'm holding off on Windows Store updates until I can get this resolved. (https://github.com/xanderfrangos/twinkle-tray/issues/286)

**Comment by gferreroferri** [comment]
I also get this error. Not sure if this is the same
![Screenshot 2022-09-15 085724](https://user-images.githubusercontent.com/823394/190336660-0e791d8b-f5a8-482b-8424-4f56f4781c1b.png)

**Comment by kwanghuee** [comment]
Windows 7 ![image](https://user-images.githubusercontent.com/48949268/204714828-050132bc-3807-4d50-b0e6-024f2dd151a7.png)

**Comment by xanderfrangos** [comment]
@kwanghuee Only Windows 10 and 11 are supported operating systems.

**Comment by k3davis** [comment]
Slight variation on this old issue; same overall exception

![image](https://github.com/user-attachments/assets/c12fc1fc-f5ac-4370-a6b1-cbd23b0aea78)

**Comment by felipecrs** [comment]
Same here:

![image](https://github.com/user-attachments/assets/e0e48707-b278-4da6-a0aa-fad5c61e6579)

**Comment by robertlindin** [comment]
I also get this error repeatedly, it's a shame because otherwise everything works as expected and the app is really useful for me.
I have two identical external monitos and the internal monitor of the surface pro 8 in my setup. I always get three errors following each other. I guess the channel closed is per monitor. Would really appreciate a fix! 

![Image](https://github.com/user-attachments/assets/9c836308-b7f9-4b33-bace-099f1ed92f17)
![Image](https://github.com/user-attachments/assets/febda789-63ee-434e-a057-9d6f7cab492c)
![Image](https://github.com/user-attachments/assets/6aa8862f-c6b7-4edd-90ab-3301b64fbda9)
