### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JsonLHC** [xanderfrangos/twinkle-tray#253]
![image](https://user-images.githubusercontent.com/29352258/138805456-458c2332-89f7-45a3-9815-dde2324407a1.png)

**Comment by rigiddesign** [comment]
I am also on 22489.1000 with the same issue

![Untitled](https://user-images.githubusercontent.com/24908663/139925749-4377f4a8-d72e-4dc9-a40b-47f06813a4eb.png)

**Comment by youpie** [comment]
Same here

**Comment by RakSrinaNa** [comment]
On 22499.211105-1550
![image](https://user-images.githubusercontent.com/1688389/141688626-adb934f8-653a-4c3f-bb6b-13a7c1dd29e6.png)

**Comment by Krutonium** [comment]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:705:16)
    at C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1032:20
    at new Promise (<anonymous>)
    at refreshMonitorsJob (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1031:16)
    at refreshMonitors (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1091:25)
    at tryEagerUpdate (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1932:5)
    at Object.<anonymous> (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1881:5)
    at Object.emit (events.js:315:20)

[OK]


[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:705:16)
    at C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1032:20
    at new Promise (<anonymous>)
    at refreshMonitorsJob (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1031:16)
    at refreshMonitors (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1091:25)
    at tryEagerUpdate (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1932:5)
    at Object.<anonymous> (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1881:5)
    at Object.emit (events.js:315:20)

[OK]

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:705:16)
    at processSettings (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:450:18)
    at getSettings (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:844:3)
    at toggleTray (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1955:5)
    at Object.<anonymous> (C:\Users\pfckr\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1872:32)
    at Object.emit (events.js:315:20)

[OK]


The text of the three errors. Windows 11 Pro Insider Preview 22499.rs_prelease.211105-1550

**Comment by xanderfrangos** [comment]
Thanks for reporting the issue! Since there are several open Issues for this bug, I'm closing all duplicates. [Subscribe to this Issue for updates as I look into this.](https://github.com/xanderfrangos/twinkle-tray/issues/246)
