### ISSUE TITLE
Using multiple monitors crashes program on boot.

### ISSUE THREAD

**Issue by keeganatorr** [xanderfrangos/twinkle-tray#36]
Error given:
```
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Failed to get physical monitor count.
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```
On version 1.9.0

**Comment by xanderfrangos** [comment]
@keeganatorr Do you mind trying [v1.8.6](https://github.com/xanderfrangos/twinkle-tray/releases/download/v1.8.6/Twinkle.Tray.v1.8.6.exe) and letting me know if you get the same error?

**Comment by keeganatorr** [comment]
Sorry seems like my monitor was just not sending DDC messages even though it was on, resetting the computer fixed it.
