### ISSUE TITLE
Frequent huge CPU consumption

### ISSUE THREAD

**Issue by phenetas** [xanderfrangos/twinkle-tray#493]
Hello, 

I am on Windows 11, and uses Twinkle Tray v1.14.7.

Frequently I notice the app consume a huge part of my CPU which is a Ryzen 5 5600H on a Lenovo Legion 5 laptop.

Please see the screenshot below showing sometime TT using 80/90% of the CPU for something between 20 and 30 seconds, and then releases it.
It is reproducible at each Windows boot. And from time to time it happens.

I uses 3 screens (2 external + 1 from the laptop)

The problem is that my fans go crazy when this happen, and it is loud for a few seconds.
Is this known? And is there a way to prevent that?

![image](https://user-images.githubusercontent.com/12865804/203531015-c192d9fb-a235-4543-bfbc-a855d4dc8e7c.png)
![image](https://user-images.githubusercontent.com/12865804/203531519-755b08b7-cfb6-4edf-8c4f-54ff8d4163d5.png)

**Comment by xanderfrangos** [comment]
Hi @phenetas,

That's very weird. I'm not able to replicate it on any of my devices.

If you're not using the Microsoft Store version, you can hopefully find out what's going on by doing this.

1. Close Twinkle Tray.
2. Open Command Prompt
3. Run `"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe" -console`
4. Reproduce the issue and check what is logged by the console.

Then copy/paste it here and I can see about resolving the issue. I recently added extra logging to the console, so please update to v1.14.8 if possible.

Thanks!

**Comment by phenetas** [comment]
Thanks for your fast answer. I was using the Store version, but I replaced it with the .exe one for the test.
Here is the log.
While writing this, TT uses around 50% of my CPU and 670Mo of Ram.

>C:\Users\phene>
Starting Twinkle Tray...
Unloaded module: uuid/v4
Function: getThemeRegistry
Monitor.js starting. If you see this more than once, something bad happened.
Running wmi-bridge test...
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e

-------------- Refresh Monitors --------------
Doing full refresh.
WMI-BRIDGE TEST: READY
WMI-BRIDGE TEST: OK
getMonitorsWMIC() Total: 55ms
getMonitorsWin32() Total: 1ms
Event: handleMonitorChange
Pausing mouse events...
Event: handleBackgroundUpdate
Checking for updates...
Unloaded module: node-fetch
Found version: v1.14.8
Event: handleBackgroundUpdate
getFeaturesDDC() Total: 6283ms
getBrightnessWMIC() Total: 85ms
getAllMonitors() total: 6427ms
Monitors found: 5&64287e1&0&UID256,5&935f3ea&0&UID4352,5&935f3ea&0&UID4354
----------------------------------------------
Setting brightness for known displays false false 1
Creating panel...

-------------- Refresh Monitors --------------
Doing full refresh.
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e
Function: getThemeRegistry
Function: getThemeRegistry
Panel ready!
~~~~~ MAIN WINDOW MINIMIZED ~~~~~~
getMonitorsWMIC() Total: 260ms
getMonitorsWin32() Total: 5ms
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e
getFeaturesDDC() Total: 5789ms
getBrightnessWMIC() Total: 116ms
getAllMonitors() total: 6177ms
Monitors found: 5&64287e1&0&UID256,5&935f3ea&0&UID4352,5&935f3ea&0&UID4354
===--- NO CHANGE ---===
----------------------------------------------

-------------- Refresh Monitors --------------
Doing full refresh.
getMonitorsWMIC() Total: 95ms
getMonitorsWin32() Total: 1ms
getFeaturesDDC() Total: 5799ms
getBrightnessWMIC() Total: 288ms
getAllMonitors() total: 6188ms
Monitors found: 5&64287e1&0&UID256,5&935f3ea&0&UID4352,5&935f3ea&0&UID4354
===--- NO CHANGE ---===
----------------------------------------------

-------------- Refresh Monitors --------------
Resuming mouse events...
getBrightnessWMIC() Total: 116ms
===--- NO CHANGE ---===
----------------------------------------------
Event: theme updated
Function: getThemeRegistry
Event: theme updated
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: theme updated
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry

-------------- Refresh Monitors --------------
getBrightnessWMIC() Total: 374ms
===--- NO CHANGE ---===
----------------------------------------------
Function: getThemeRegistry
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e
~~~~~ MAIN WINDOW RESTORED ~~~~~~
Pausing mouse events...
~~~~~ MAIN WINDOW MINIMIZED ~~~~~~
Saved known displays!
Event: theme updated
Function: getThemeRegistry
Event: theme updated
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: theme updated
Function: getThemeRegistry
Event: theme updated
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Event: handleAccentChange
Function: getThemeRegistry
Ev

**Comment by xanderfrangos** [comment]
According to that, something on your PC is triggering a bunch of theme changes in Windows. Do you have any 3rd party software that changes your theme (dark/light mode) or accent color?

**Comment by phenetas** [comment]
Nope, nothing that I am aware of.
I tend to keep my PC clean with the least possible tweaks and softs installed. I think twice before installing anything.

I use Windows dark mode (native). And my wallpaper is a static image.

**Comment by xanderfrangos** [comment]
Perhaps there's some Lenovo software on the laptop that's triggering the theme changes?

**Comment by phenetas** [comment]
I have this from Lenovo Vantage running in the background. How do I stop it from running ? for a few minutes so I can test.

![image](https://user-images.githubusercontent.com/12865804/203656182-6ecc81f3-dbeb-4eec-a9ae-9b86ce8ee00e.png)

**Comment by phenetas** [comment]
Ok so, I've manually killed every LenovoVantage process I could see. Closed all my opened Chrome windows, and closed everything possible except for 1 Firefox window + task manager + cmd

Redo the same test, and this time TT did not use any CPU.

Here is a log dump:

> 
C:\Users\phene>
Starting Twinkle Tray...
Unloaded module: uuid/v4
Function: getThemeRegistry
Monitor.js starting. If you see this more than once, something bad happened.
Running wmi-bridge test...
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e

-------------- Refresh Monitors --------------
Doing full refresh.
WMI-BRIDGE TEST: READY
WMI-BRIDGE TEST: OK
getMonitorsWMIC() Total: 62ms
getMonitorsWin32() Total: 1ms
Event: handleMonitorChange
Pausing mouse events...
Event: handleBackgroundUpdate
Checking for updates...
Unloaded module: node-fetch
Found version: v1.14.8
Event: handleBackgroundUpdate
Couldn't refresh monitors Monitor thread timed out.
----------------------------------------------
Setting brightness for known displays false false 1
Could not update brightness

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at updateBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1354:24)
    at applyProfile (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:631:11)
    at setKnownBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:605:3)
    at C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:2183:39

Could not update brightness

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at updateBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1354:24)
    at applyProfile (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:631:11)
    at setKnownBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:605:3)
    at C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:2183:39

Could not update brightness

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at updateBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:1354:24)
    at applyProfile (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:631:11)
    at setKnownBrightness (C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:605:3)
    at C:\Users\phene\AppData\Local\Programs\twinkle-tray\resources\app.asar\src\electron.js:2183:39

Creating panel...

-------------- Refresh Monitors --------------
Doing full refresh.
Analytics: sending with UUID c9dd3fb4-cc83-4506-b5f5-aafd888f2c7e
Function: getThemeRegistry
Function: getThemeRegistry
Panel ready!
Thread busy. Cancelling refresh.
Couldn't refresh monitors No monitors recieved!
----------------------------------------------
~~~~~ MAIN WINDOW MINIMIZED ~~~~~~
Unloaded module: sharp
Unloaded module: sharp
getFeaturesDDC Timed out.
getFeaturesDDC() failed! {}
getBrightnessWMIC() Total: 318ms
getBrightnessWMI() skipped due to previous failure.
getAllMonitors() total: 15884ms
Monitors found: 5&64287e1&0&UID256,5&935f3ea&0&UID4354,5&935f3ea&0&UID4352
Unloaded module: sharp
Unloaded module: sharp

-------------- Refresh Monitors --------------
Doing full refresh.
getMonitorsWMIC() Total: 56ms
getMonitorsWMI() skipped due to previous failure.
getMonitorsWin32() Total: 0ms
getFeaturesDDC() Total: 5841ms
getBrightnessWMIC() Total: 67ms
getBrightnessWMI() skipped due to previous failure.
getAllMonitors() total: 5967ms
Monitors found: 5&64287e1&0&UID256,5&935f3ea&0&UID4354,5&935f3ea&0&UID4352
----------------------------------------------
Event: handleBackgroundUpdate

**Comment by xanderfrangos** [comment]
Yeah, looks like whatever you closed fixed it. I guess restart your PC and try tinkering with the Lenovo Vantage software. Whatever is causing the theme update spam hopefully can be turned off without disabling/uninstalling the LenovoVantage service entirely.

**Comment by Kodehawa** [comment]
Still an issue on 1.15.1.

**Comment by Kodehawa** [comment]
This happens with so much as switching desktops. No external application needed for that to be absolutely spammed (and my CPU jumping to 100%) :P

Switching desktops isn't the only thing that seems to trigger it, changing wallpaper or similar stuff also causes it (which would cause it if you have a wallpaper change every few)

**Comment by xanderfrangos** [comment]
@Kodehawa Theme changes are tracked for:

1. Detecting accent color
2. Detecting light/dark theme
3. Detecting and processing the current wallpaper for the fake "Mica" effect

I've made some improvements for v1.15.2 that should significantly reduce CPU usage when the theme changes. I'm getting 2-3% usage in Twinkle Tray when switching wallpapers now (13700k), so I'm guessing you'll see like 3-5% on your CPU.

**Comment by Kodehawa** [comment]
I just realized this is an electron app and not a native WinUI 3 application. Geez that's a pretty good imitation of the WinUI interface haha.

I'll give it a shot. Thanks you :)

**Comment by Kodehawa** [comment]
Haven't pushed it to the MS Store? I'd have preferred to update it there. Maybe MS is just delaying sending it :P

**Comment by xanderfrangos** [comment]
@Kodehawa Microsoft can take a while. I pushed it at the same time as GitHub:

![Screenshot_20221211-141029](https://user-images.githubusercontent.com/33106561/206923841-320807ee-5dc9-418b-b0a1-6966f320051b.png)

**Comment by Kodehawa** [comment]
![image](https://user-images.githubusercontent.com/20606963/206959333-e242ab08-d91d-4b69-b7cf-1fb430a567eb.png)

Yep, way better now :)

**Comment by ryush00** [comment]
![Image](https://github.com/user-attachments/assets/4a6ac597-8170-41d8-b040-a2d7246fa8b6)

I’m using Twinkle Tray version 1.16.7.
I just experienced a similar issue. When I woke the screen (by moving the mouse), the computer became unresponsive. I opened Task Manager and saw that Twinkle Tray was consuming a lot of system resources. After I killed the process and restarted it, everything returned to normal. So I’m reporting it here.
