### ISSUE TITLE
Update dev/build instructions to current (2023) dependencies

### ISSUE THREAD

**Issue by silviuk** [xanderfrangos/twinkle-tray#557]
I'd like to extend twinkle-tray with a few shortcuts to set the windows Dark and Light mode without an extra tool.

Following the readme "Build Instructions", I'm getting stuck at `npm install` with lots of "deprecated" and "no longer maintained" log messages for underlying dependencies of twinkle-tray. 

I have installed the most recent versions of:
- Visual Studio Community 2022 (64-bit) (with C++ Desktop development package, build-tools etc.)
- Python
- Node.js and
- node-gyp

Can anyone provide guidance or update the build instructions? Seems that the build instructions are a bit old, based on Visual Studio 2017. I'm not an expert on Windows or node.js development.

Console output below, full log attached.
```
PS C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray> npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\silvi\\OneDrive\\Documente\\workspace\\twinkle-tray\\node_modules\\electron',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\electron'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\silvi\\OneDrive\\Documente\\workspace\\twinkle-tray\\node_modules\\electron'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run rebuild
npm ERR! > win32-displayconfig@0.1.0 rebuild
npm ERR! > node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@6.1.0
npm ERR! gyp info using node@18.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2022
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\silvi\\OneDrive\\Documente\\workspace\\twinkle-tray\\node_modules\\win32-displayconfig\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\silvi\OneDrive\Documente\workspace\twinkle-tray\node_modules\win32-displayconfig
npm ERR! gyp ERR! node -v v18.14.2
npm ERR! gyp ERR! node-gyp -v v6.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\silvi\AppData\Local\npm-cache\_logs\2023-03-05T15_40_36_907Z-debug-0.log
```

[2023-03-05T15_40_36_907Z-debug-0.log](https://github.com/xanderfrangos/twinkle-tray/files/10892202/2023-03-05T15_40_36_907Z-debug-0.log)

**Comment by lulle2007200** [comment]
Main issue is old node-gyp versions not supporting MSVC 2022 and Windows 11 SDKs. Override the node-gyp version in package.json to 9.4.1 or later, e.g. add:
`"overrides":{node-gyp: 9.4.1}`

**Comment by xanderfrangos** [comment]
@lulle2007200 FYI, the beta branch has been updated to build much more cleanly. I'm still working out some bugs with the app itself, but the new build process shouldn't require hacks or workarounds any more.

**Comment by xanderfrangos** [comment]
I've backported the build process fixes from the beta branch. The master branch should build properly now.
