### ISSUE TITLE
Explain build instructions

### ISSUE THREAD

**Issue by bluin4308** [xanderfrangos/twinkle-tray#849]
Please, write more details on environment requirements to build an app.
Using WSL 2 with Ubuntu 22 on Win 11, I'm still getting the next error
`Error: Module did not self-register: '/mnt/c/Users/User/Desktop/twinkle-tray/node_modules/win32-displayconfig/build/Release/win32_displayconfig.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/mnt/c/Users/User/Desktop/twinkle-tray/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/mnt/c/Users/User/Desktop/twinkle-tray/node_modules/win32-displayconfig/index.js:6:34)`

**Comment by xanderfrangos** [comment]
Twinkle Tray must be built on Windows. WSL won't work. I've updated the build instructions with this detail. 👍
